### ISSUE TITLE
Car plugin Cable - disable loading

### ISSUE THREAD

**Issue by aichingerk** [dupondje/nrgkick-ha#3]
Hi, can anyone share their automation when the cable is plugged into the car that the charging is disabled.
Maybe also your automation for normal loading, how you have solved this.
Thx

**Comment by aichingerk** [comment]
Hi, can you explain your xxx between sensor and control_pilot_status and switch charging_state ?
I do not find any information about this xxx in the web. i know it's a placeholder, but i can't figure out for what. and without it the automation doesn't work. here i always get an error like: Referenced entities switch.charging_state are missing or not currently available

**Comment by dupondje** [comment]
The sensor name contains the NRGKick name. So it depends...
Check the sensor name in your HA setup..

**Comment by aichingerk** [comment]
It is without xxx
![image](https://github.com/dupondje/nrgkick-ha/assets/82718567/733bcbad-9122-4b33-b493-b4fe9d95d067)
and 
![image](https://github.com/dupondje/nrgkick-ha/assets/82718567/0a7e5729-eb68-4743-b77d-047b5f0d0bfc)

what does the warning mean in the log ?
![image](https://github.com/dupondje/nrgkick-ha/assets/82718567/8cec09a1-cd5b-454a-bd48-0527abb48bb9)

Actually it is not possible to stop loading, when i connect the nrg kick to the car.

**Comment by dupondje** [comment]
Try creating the automation from the UI.
This is some very basic HA automation really...

**Comment by aichingerk** [comment]
Yes, you are right. It is a very basic HA automation.
For turn_off it is a switch service and not a input_boolean and for setting  a charge_current_limit also a service call is needed with number.

This example is only for other user, when the want to do this and the example for change current_limit.

```
alias: CAR NRGKick disable loading on connect
trigger:
  - platform: state
    entity_id: sensor.control_pilot_status
    from: NRG_CP_A_STANDBY
    to: NRG_CP_B_CONNECTED
action:
  - service: number.set_value
    target:
      entity_id: number.charge_current_limit
    data:
      value: "8"
    enabled: false
  - service: switch.turn_off
    target:
      entity_id: switch.charging_state
    data: {}
mode: single
```
